on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    environment: Development

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Create Build folder
        run: mkdir -f /home/runner/work/CV-Frontend/CV-Frontend/build

      - name: Build project
        run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: './build'